theme = "mycatppuccin"

[editor]
bufferline = "multiple"
line-number = "relative"
true-color = true
rulers = [80]
cursorline = true
color-modes = true
scrolloff = 12
idle-timeout = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode"]
center = ["file-modification-indicator", "file-name"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal."backspace"]
c = ":config-open"
r = ":config-reload"
w = ":write"
q = ":quit"

[editor.file-picker]
hidden = false

