theme = "mycatppuccin"

[editor]
mouse = false
bufferline = "multiple"
true-color = true
cursorline = true
color-modes = true
scrolloff = 12
idle-timeout = 75

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-modification-indicator", "file-name"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal."backspace"]
c = ":config-open"
r = ":config-reload"
w = ":write"
q = ":quit"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
